version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: islamic-prayer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: islamic-prayer-tools
    volumes:
      - mongodb_data:/data/db
      - ./server/src/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: islamic-prayer-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/islamic-prayer-tools?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: islamic-prayer-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data: